### ISSUE TITLE
conbench CLI: adapter.post_results(): does not retry upon 504

### ISSUE THREAD

**Issue by jgehrcke** [voltrondata-labs/arrow-benchmarks-ci#121]
I had a closer look at https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2988#01887053-52f4-4a95-a6bc-73f454342c75 to see which code actually runs for doing HTTP interaction:

```
[230531-03:04:46.395] [49508] [benchclients.logging] ERROR: Response content: <html>

<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>


Traceback (most recent call last):
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/bin/conbench", line 8, in <module>
    sys.exit(conbench())
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/conbench/cli.py", line 149, in _benchmark
    for result, output in benchmark().run(**kwargs):
  File "/opt/homebrew/var/buildkite-agent/builds/test-mac-arm/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/benchmarks/benchmarks/cpp_micro_benchmarks.py", line 130, in run
    self.adapter.post_results()
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/_adapter.py", line 187, in post_results
    res = client.post(path="/benchmarks/", json=result_dict)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchclients/base.py", line 64, in post
    self._maybe_raise(req_string=req_string, res=res)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchclients/base.py", line 85, in _maybe_raise
    res.raise_for_status()
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://conbench.ursa.dev//api/benchmarks/
```

So, this seems to be the legacy Conbench CLI (`/conbench/cli.py"`). _But_ it's seemingly using the 'more mordern' HTTP client stack (`benchadapt/adapters/_adapter.py`). That however, seems to be in a state where it's not doing retrying in view of 5xx. That is a clear bug. That seems to be the version prior to introduction of RetryingHTTPCLient.

https://github.com/conbench/conbench/blob/81a0272cc28c8bd10d3f993d58c0f63efbff8f02/benchclients/python/benchclients/conbench.py#L24

**Comment by jgehrcke** [comment]
Definition of done: when we see explicit log statements emitted by RetryingHTTPClient.

**Comment by jgehrcke** [comment]
Seemingly via https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/ad5e8b2ce28a35e6786e02491d7a523787f51256/adapters/requirements.txt#L1 we refer implicitly to benchadapt 2023.2.8.

Let's bump this to head of main. Let's version-pin? Also see https://github.com/voltrondata-labs/benchmarks/blob/a85348ab642d7ced05d3f10cbee0c282e577f1c3/requirements.txt#L4

**Comment by austin3dickey** [comment]
This is a very complex dependency tree. I opened https://github.com/voltrondata-labs/benchmarks/pull/135 to see if pinning the versions in that repo helps. Ultimately, we are using the `conbench` legacy CLI for most benchmarks. I'm still not sure how we're getting that "Initializing adapter" log statement. We might need some help from @alistaire47 here.

**Comment by austin3dickey** [comment]
If that works, arrowbench will also be tricky - we need to install the new `benchclents` from R like we do [here](https://github.com/voltrondata-labs/arrowbench/blob/ebfab3d5535a1a7ba8680be4d0394296b9b1a5ee/R/external-dependencies.R#L63).

**Comment by jgehrcke** [comment]
Still not working. Looking at this log output from recently:
```
[230601-02:47:51.646] [2702278] [buildkite.benchmark.run] INFO: Started executing -> conbench js-micro  --run-id=$RUN_ID --run-name="$RUN_NAME" --run-reason="$RUN_REASON"
[230601-02:56:14.785] [2702278] [buildkite.benchmark.run] INFO: [230601-02:47:52.433] [2751630] [benchadapt.adapters] INFO: Initializing adapter
[230601-02:56:08.794] [2751630] [root] INFO: Time to POST https://conbench.ursa.dev/api/login/: 0.27878 s
[230601-02:56:08.875] [2751630] [root] INFO: Time to POST https://conbench.ursa.dev/api/benchmarks/: 0.08107 s
```
I now understand that the msgs containing ` [2751630] [root] ` is the stderr of the child process. So, we call an executable called `conbench` -- but what is that, really? Is that the legacy CLI? If it is, I can't don't see how it includes benchadapt.

**Comment by jgehrcke** [comment]
Found how benchadapt leaks in to the legacy CLI:
https://github.com/voltrondata-labs/benchmarks/blob/e455d72cfd583f1681ed126b2ade476843cd827d/benchmarks/cpp_micro_benchmarks.py

```
import conbench.runner
from benchadapt.adapters import ArcheryAdapter
from benchadapt.log import log
```

and later
```
        if not os.environ.get("DRY_RUN"):
            self.adapter.post_results()
```

**Comment by austin3dickey** [comment]
I saw that too -- but theoretically that should only affect the `cpp-micro` benchmarks, not the other benchmarks in that repo like `js-micro`, right? That's why I'm so confused about the log statement.

**Comment by austin3dickey** [comment]
Diving into this more. Using https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2966 for reference because it's a quick, relatively simple benchmarking job.

Start the benchmarking step with
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/pipeline.yml#L3

That runs this. (`BENCHMARKABLE_TYPE=arrow-commit` in this case.)
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/utils.sh#L122-L157

We set up arrow and test that pyarrow is built. That gets us to [this point](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2966#01887783-a714-47d4-ab2c-63d7e2aaaa1a/33-4575) in the logs. Then
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/utils.sh#L155

which calls
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/utils.sh#L76

Okay, that's the first interesting part. That's a wheel of the legacy CLI from PyPI. (We auto-tag the state of the repo at the time of publishing those wheels: https://github.com/conbench/conbench/tree/conbench-2023.4.6.) But it's not installing `benchadapt` or `benchclients` yet. We're now at [this point](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2966#01887783-a714-47d4-ab2c-63d7e2aaaa1a/33-4599) in the logs.

Next
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/utils.sh#L156

which calls
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run_benchmark_groups.py#L6-L10

which runs this big method for a few different benchmarking repositories, including `voltrondata-labs/benchmarks`, `voltrondata-labs/arrowbench`, and `voltrondata-labs/arrow-benchmarks-ci`.
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L655-L695

Let's start with `voltrondata-labs/benchmarks`. Post to a tracking API. Clone, fetch, and checkout the benchmarking repo. Run the setup commands:
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L38

This installs https://github.com/voltrondata-labs/benchmarks which brings in our [newly-pinned dependencies](https://github.com/voltrondata-labs/benchmarks/blob/e455d72cfd583f1681ed126b2ade476843cd827d/requirements.txt):
```
benchadapt@git+https://github.com/conbench/conbench.git@81a0272cc2#subdirectory=benchadapt/python
benchclients@git+https://github.com/conbench/conbench.git@81a0272cc2#subdirectory=benchclients/python
```
Now we're at [this point](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2966#01887783-a714-47d4-ab2c-63d7e2aaaa1a/33-4668) in the logs.

Continue onward. Set up a `.conbench` file (the legacy CLI way to provide credentials). Set a few env vars. Read [this JSON file](https://github.com/voltrondata-labs/benchmarks/blob/e455d72cfd583f1681ed126b2ade476843cd827d/benchmarks.json) to get details about all benchmarks in this repo. Since none of them have the `"runner"` key set, default to the `"conbench"` runner:
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L549

Filter to only [these two](https://github.com/voltrondata-labs/benchmarks/blob/e455d72cfd583f1681ed126b2ade476843cd827d/benchmarks.json#L50-L63) benchmarks since they match this job's filter of `{'langs': {'Python': {'names': ['dataset-read', 'dataset-select']}}}`. Continue to the meat of the code.

We're only running Python benchmarks; simple. Next step is to run lang-specific benchmark commands:
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L618-L622
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L88

^ That's just a quick step that creates a directory. Next we actually get to run benchmarks! Choose the `ConbenchBenchmarkGroupsRunner` because like I mentioned above that's what we default to.
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L682-L686

That calls `run_benchmark_groups()`.
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L381-L407

Print env vars. Log [this dict](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2966#01887783-a714-47d4-ab2c-63d7e2aaaa1a/33-4892) to a tracking API. Start a [memory-monitoring job](https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/monitor_memory.py). Run the command:
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/6aff3a0027b71ebe32b36a36fc85480f76b0904a/buildkite/benchmark/run.py#L213

Now I have to assume this is the `conbench` executable we installed above, because we never re-installed the `conbench` library after that. So now we're in legacy-conbench-land. Calling `conbench dataset-read ...` enters us [here](https://github.com/conbench/conbench/blob/conbench-2023.4.6/conbench/cli.py#L149), where `benchmark()` is an instance of the [DatasetReadBenchmark](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/dataset_read_benchmark.py#L10). Its `run()` method is [here](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/dataset_read_benchmark.py#L25).

Okay, before I continue onward, I have a thought. Let me post this for now.

**Comment by austin3dickey** [comment]
Okay, new thought.
```
> conbench --help
[230601-14:09:50.383] [78544] [benchadapt.adapters] INFO: Initializing adapter
Usage: conbench [OPTIONS] COMMAND [ARGS]...

  Conbench: Language-independent Continuous Benchmarking (CB) Framework

Options:
  --help  Show this message and exit.

Commands:
  cpp-micro                   Run the Arrow C++ micro benchmarks.
  csv-read                    Run csv-read benchmark(s).
  csv-write                   Run csv-write benchmark(s).
  ...etc...
```
*Whenever* we run the `conbench` executable from the root of the https://github.com/voltrondata-labs/benchmarks repo, we go through the [benchmark registry process](https://github.com/conbench/conbench/blob/conbench-2023.4.6/conbench/runner.py#L26), which initializes all the benchmark classes, including the `cpp-micro` class, which [sets up an adapter](https://github.com/voltrondata-labs/benchmarks/blob/e455d72cfd583f1681ed126b2ade476843cd827d/benchmarks/cpp_micro_benchmarks.py#L103). That's why we get the `Initializing adapter` log statement. It has nothing to do with running the benchmarks. 🙃 Just calling the executable.

So that means we are COMPLETELY relying on the `conbench` legacy CLI [client](https://github.com/conbench/conbench/blob/13af148b988e5cd7211c9619025ecb6472045e2e/conbench/util.py#L166-L177) for interacting with Conbench for all these benchmarks (except for `cpp-micro`). Even though we have the correct version of `benchclients` with the `RetryingHTTPClient`, it won't be used until we migrate everything over to `benchadapt`, or at least `benchconnect`. Mystery solved. Though of course this means a lot more work to complete this ticket.

Sure enough, we do now see the `RetryingHTTPClient` logs in the `cpp-micro` benchmarks!!
https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-thinkcentre-m75q/builds/2988#01887731-5725-49ea-b2e6-04b064ac0e0d
```
[230601-10:39:05.836] [3250580] [benchadapt.adapters] INFO: Initializing conbench client
[230601-10:39:05.836] [3250580] [benchclients.conbench] INFO: try to perform login
[230601-10:39:05.836] [3250580] [benchclients.http] INFO: try: POST to https://conbench.ursa.dev/api/login/
[230601-10:39:06.101] [3250580] [benchclients.http] INFO: POST request to https://conbench.ursa.dev/api/login/: took 0.2652 s, response status code: 204
[230601-10:39:06.102] [3250580] [benchclients.conbench] INFO: ConbenchClient: initialized
[230601-10:39:06.102] [3250580] [benchadapt.adapters] INFO: Posting results to conbench
[230601-10:39:06.102] [3250580] [benchclients.http] DEBUG: POST request JSON body:
{
  "run_name": "commit: e44bcafc8db2441f5e18ebb27fd7e0fdba580148",
  "run_id": "131747c1759345ed8d37406a312c737f",
...
```

**Comment by jgehrcke** [comment]
Thank you for going deep here and for documenting the findings in detail @austin3dickey!

> we do now see the RetryingHTTPClient logs in the cpp-micro benchmarks!!

OK, so some bumping has helped. Great.

>relying on the conbench legacy CLI [client](https://github.com/conbench/conbench/blob/13af148b988e5cd7211c9619025ecb6472045e2e/conbench/util.py#L166-L177) for interacting with Conbench for all these benchmarks (except for cpp-micro).

An important conclusion!

**Comment by austin3dickey** [comment]
From @alistaire47, lightly edited for clarity:

>A full changeover from the legacy `conbench` CLI to `benchadapt` would be a big lift, and would require something to actually run the benchmarks still (the new `benchrun` library was intended for this purpose, but hasn’t been fully tested yet). So it’s close to a full rewrite of https://github.com/voltrondata-labs/benchmarks; on the `arrow-benchmarks-ci` side it could leverage the code I recently added for running adapters directly.
>
>Just switching in `benchclients` for posting is much more doable, though it will require a good amount of rearranging data.

I agree, though actually I'm not sure how much rearranging data we'll need to use `benchclients`. I'm wondering if we can "just" override the [publish()](https://github.com/conbench/conbench/blob/main/conbench/util.py#L193-L194) method of [this class](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_benchmark.py#L55) that `voltrondata-labs/benchmarks` uses as a base class for all its custom benchmarks.

**Comment by austin3dickey** [comment]
Solved in 
- https://github.com/voltrondata-labs/benchmarks/pull/136
- https://github.com/voltrondata-labs/benchmarks/pull/137
- https://github.com/voltrondata-labs/benchmarks/pull/138
- https://github.com/voltrondata-labs/benchmarks/pull/140

All benchmark logs are showing the new ConbenchClient log messages now.
